# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_commentpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='moder',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
