# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='category', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='post.Category'),
        ),
    ]
