# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20171212_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='Текст статьи'),
        ),
    ]
